### ISSUE TITLE
FluffyUI static constructor

### ISSUE THREAD

**Issue by FluffierThanThou** [fluffy-mods/ModManager#101]
Reported by: __Mr_Krill__
Description:
2 Yellow error
 <a class="bb_link" href="https://steamcommunity.com/linkfilter/?url=https://gist.github.com/efd4badfdd250f3422658679f011eaed" target="_blank" rel="noreferrer">https://gist.github.com/efd4badfdd250f3422658679f011eaed</a> <br><br>Type &lt;FluffyUI.TextureChooser&gt; from &lt;fluffy.modmanager&gt;'s &lt;FluffyUI&gt; probably needs a StaticConstructorOnStartup attribute, because it has a field &lt;LeftArrow&gt; of type &lt;UnityEngine.Texture2D&gt;. All assets must be loaded in the main thread.<br>Verse.Log:Warning(String, Boolean)<br>Revolus.BetterReportProbablyMissingAttributes.Patch_Verse_StaticConstructorOnStartupUtility_ReportProbablyMissingAttributes:Replace()<br><br>Type &lt;FluffyUI.TextureChooser&gt; from &lt;fluffy.worktab&gt;'s &lt;FluffyUI&gt; probably needs a StaticConstructorOnStartup attribute, because it has a field &lt;LeftArrow&gt; of type &lt;UnityEngine.Texture2D&gt;. All assets must be loaded in the main thread.<br>Verse.Log:Warning(String, Boolean)<br>Revolus.BetterReportProbablyMissingAttributes.Patch_Verse_StaticConstructorOnStartupUtility_ReportProbablyMissingAttributes:Replace()

**Comment by Ano-Nymus** [comment]
The first warning message is indeed caused by modmanager, see log below (only using harmony and modmanager).

I would really like to see this warning fixed, but failed at compiling the source code myself.
It should be really easy to fix though, with the explanation of the issue found [here](https://rimworldwiki.com/wiki/Modding_Tutorials/Hello_World).

Type TextureChooser probably needs a StaticConstructorOnStartup attribute, because it has a field LeftArrow of type Texture2D. All assets must be loaded in the main thread.
Verse.Log:Warning(String, Boolean)
Verse.StaticConstructorOnStartupUtility:ReportProbablyMissingAttributes()
Verse.<>c:<DoPlayLoad>b__4_2()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Update()
Verse.Root_Entry:Update()
