### ISSUE TITLE
Getting in-game texture glitches running only Mod Manager (OSX)

### ISSUE THREAD

**Issue by bbforsyth** [fluffy-mods/ModManager#107]
Texture glitches in-game when running mod manager, text not rendering/displaying properly. I had over 100 mods installed and was having lots of issues with pawns standing still, so i tried to troubleshoot my entire modlist. I get no errors on a blank mod list, but as soon as I add mod manager the errors begin. 

https://gist.github.com/HugsLibRecordKeeper/c7c2498bc44804580be2928b2e5d8cbe

Images are from a previous save as the textures are flashy/stuttery and hard to capture with a screenshot

<img width="67" alt="Screen Shot 2020-08-05 at 5 30 03 pm" src="https://user-images.githubusercontent.com/69238891/89390937-d76cb980-d74a-11ea-99b7-694098f63c5f.png">

<img width="1440" alt="Screen Shot 2020-07-25 at 4 05 11 pm" src="https://user-images.githubusercontent.com/69238891/89390910-cb80f780-d74a-11ea-887a-dbdba1f65ac9.png">

OSX Catalina
Steam

**Comment by FluffierThanThou** [comment]
I highly doubt that's actually related to Mod Manager, as it should have no
ingame effect whatsoever. The graphical artifacts look more like a graphics
card that is dying/overheating, or some bad rendering calls. I've never
seen that in RimWorld though, as it isn't exactly a GPU demanding game.

I'd suggest reinstalling the game (or verifying the game files with steam),
and looking around if there's a driver update for your GPU. If you still
suspect Mod Manager after that, please add a player.log so that I can have
a closer look.
