### ISSUE TITLE
Increasing UI lag as mods are made active

### ISSUE THREAD

**Issue by xXXStrykerXXx** [fluffy-mods/ModManager#70]
**Describe the bug**  
As mods are set to active within the Mod Manager interface, the 'lag' increases gradually. Even at 10 mods loaded to active, it was extremely slow.

**Expected behavior**  
Reasonable speed when selecting and managing mods

**Steps to reproduce**  

1. Load Mod Manager version 2.0.880.
2. Set mods to active one by one (loading a list works but results in horrendous lag).
3. Watch UI lag increase dramatically.

**Other mods**  
No other mods are involved at the moment, aside from Harmony; tried both with and without Harmony as well.

**Output log**  
https://gist.github.com/5ed67b3afe62184eec9789fab7a81ca2
This is the log from after loading 11 mods to active. No restarts or other actions.

**Save game**  
Not applicable

**Screenshots**  
Not applicable, UI lag increases slowly as mods are added

**Environment**  
 - OS: Windows 10
 - 64 bits
 
**Game**
 - 64 bits
 - Steam
 - Version: 1.1.2562

**Comment by Whyareuhere** [comment]
Associated Bug:
In addition, when clicking and dragging mods in Mod Manager, sometimes the cursor accidentally grabs the mod below it instead of the mod you are clicking.

Steps to Reproduce:
Load many mods (about 30 to 40)
Drag a mod. Mod should be the one below it if clicking on the bottom-half of the mod being dragged.

Other mods:
No other mods seem to be the issue. This occurs when mods of any type are loaded into Rimworld.

Does not affect save game or output log.

Environment:
Windows 10 OS, 64 bit
Steam
Version 1.1.2562

**Comment by Roshag** [comment]
There is the same problem with vanilla game, but with larger amount of mods. The problem with Mod Manager is caused by a large list of inactive mods - there are no lags when using the search bar

**Comment by Roshag** [comment]
And JecsTools creates a large amount of lags - something is very wrong with its dependencies - a bunch of "Not applicable"
